##CFT for creating SecurityGroup
AWSTemplateFormatVersion: '2010-09-09'
Description: Provision a simple Amazon Linux Instance and allow SSH connectivity.
Parameters:
  TheCloudNationVpcId:
    Description: 'VPC for creating instance using CFT'
    # Type: AWS::EC2::VPC::Id
    Type: String
    Default: vpc-0b2075324eb857dc6

Resources:
  TheCloudNationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Batch11 Security Group for test purpose
      GroupName: TheCloudNationSecurityGroup
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: !Ref TheCloudNationVpcId           
      Tags: 
        - Key: "Name"
          Value: "TheCloudNationSecurityGroup"

Outputs:
  SecurityGroup:
    Description: Security Group for creating test instances
    Value: !Ref TheCloudNationSecurityGroup
    Export: 
      Name: !Sub "${AWS::StackName}-SecurityGroup"


#######################################################################################################################################################################
#######################################################################################################################################################################

##CFT for Creating EC2 instance using above EC2 instance.

AWSTemplateFormatVersion: '2010-09-09'
Description: Provision a simple Amazon Linux Instance and allow SSH connectivity.
Parameters:
  KeyPairName:
    Description: EC2 Key Pair for SSH Access, you must have created these prior to
      running this.
    Type: AWS::EC2::KeyPair::KeyName
    Default: batch11_keypair
  TheCloudNationAmiId:
    Description: 'Using Amazon Linux Image for creating this Instance'
    Type: String
    Default: ami-03b644b4d078605bd

  TheCloudNationInstanceType:
    Description: 'Instance type configuration'
    Type: String
    Default: t3.micro

Resources:
  TheCloudNationInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPairName
      ImageId: !Ref TheCloudNationAmiId
      InstanceType: !Ref TheCloudNationInstanceType
      SecurityGroupIds:
        - !ImportValue test-stack-SecurityGroup
      Tags:
        - Key: "Name"
          Value: "TheCloudNation Instance"    
